name: qrpay
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.6.0+17

environment:
  sdk: ">=3.4.3 <4.2.0"
  flutter: 3.22.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  # manually added dependency
  get: 4.6.6
  flutter_screenutil: ^5.5.3+2
  google_fonts: 5.1.0
  country_code_picker: 3.0.0
  get_storage: ^2.0.3
  logger: 2.1.0
  pin_code_fields: 8.0.1
  intl: ^0.19.0
  image_picker: 1.0.7
  dotted_line: 3.2.2
  flutter_svg:
  percent_indicator: ^4.2.3
  qr_code_scanner: ^1.0.1
  flip_card: ^0.7.0
  dotted_border: 2.1.0
  carousel_slider: ^4.2.1
  flutter_launcher_icons:
  connectivity_plus: 5.0.2
  flutter_spinkit: ^5.1.0
  awesome_snackbar_content: ^0.1.1
  smooth_page_indicator: ^1.1.0
  country_list_pick: ^1.0.1+6
  intl_phone_field: 3.2.0
  http: 1.2.1
  flutter_inappwebview: 5.8.0
  patterns_canvas: ^0.4.0
  flutter_html: 3.0.0-beta.2
  share_plus: 7.1.0
  local_auth: 2.2.0
  cached_network_image: 3.3.1
  path_provider: ^2.1.1
  uuid:
  flutter_local_notifications: ^16.3.0
  iconsax: ^0.0.8
  flutter_animate: 4.5.0
  flutter_staggered_animations: ^1.1.1
  qr_flutter: ^4.1.0
  liquid_swipe: ^3.1.0
  pusher_beams: ^1.1.1
  firebase_core: ^3.0.0
  jwt_decoder: ^2.0.1

dependency_overrides:
  awesome_snackbar_content: 0.1.3
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: 3.0.1
  # flutter_app_name:
  build_runner:
  flutter_gen_runner:
flutter_app_name:
  name: "QRPay User"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_launcher.png"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  #  flutter packages pub run build_runner build
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AgencyFB-Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/card/
    - assets/clipart/
    - assets/icon/
    - assets/icon/agent.svg
    - assets/logo/
    #    - assets/onboard/
    - assets/qr/
